version: '3.8'

services:
  web:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "80:00"
    depends_on:
      - redis
      - celery

  celery:
    build: .
    command: celery -A index_checker_project worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
