# Generated by Django 4.1.13 on 2023-11-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('is_indexed', models.BooleanField()),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
