# Generated by Django 4.1.13 on 2023-11-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_check', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlIndexStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1024)),
                ('is_indexed', models.CharField(choices=[('Indexed', 'Indexed'), ('Not Indexed', 'Not Indexed')], max_length=15)),
            ],
        ),
    ]
