# Generated by Django 4.1.13 on 2023-11-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_check', '0002_urlindexstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlindexstatus',
            name='is_indexed',
            field=models.CharField(blank=True, choices=[('Indexed', 'Indexed'), ('Not Indexed', 'Not Indexed')], max_length=15, null=True),
        ),
    ]
